server:
  port: ${SERVE_PORT:8086}
  servlet:
    context-path: /v1/rest
spring:
  application:
    name: rekome
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/rekome?createIfNotExists=true}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB
  cloud:
    aws:
      credentials:
        access-key: 
        secret-key: 
      s3:
        region: us-east-1
app:
  cors:
    headers: ${APP_CORS_HEADERS}
    origins: ${APP_CORS_ORIGINS}
    methods: ${APP_CORS_METHODS}
  public-key: ${APP_PUBLIC_KEY:classpath:app-pub.key}
  private-key: ${APP_PRIVATE_KEY:classpath:app.key}
  properties:
    aws-bucket: ${APP_PROPERTIES_AWS_BUCKET:rekognition-custom}
logging:
 level:
  org:
    springframework:
      web: TRACE
      security: TRACE