server:
  port: ${SERVE_PORT:8086}
  servlet:
    context-path: /v1/rest
spring:
  application:
    name: rekome
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/rekome?createIfNotExists=true}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      minimum-idle: ${APP_HIKARI_MINIMUM_IDLE:5}
      maximum-pool-size: ${APP_HIKARI_MAXIMUM_POOL_SIZE:20}
      idle-timeout: ${APP_HIKARI_IDLE_TIMEOUT:30000}
      max-lifetime: ${APP_HIKARI_MAX_LIFETIME:1800000}
      connection-timeout: ${APP_HIKARI_CONNECTION_TIMEOUT:30000}
      leak-detection-threshold: ${APP_HIKARI_LEAK_DETECTION_THRESHOLD:2000}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties: 
      hibernate:
        dialect: ${DB_HIBERNATE_DIALECT:org.hibernate.dialect.MariaDBDialect}
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB
  cloud:
    aws:
      credentials:
        access-key: ${APP_AWS_ACCESS_KEY}
        secret-key: ${APP_AWS_SECRET_KEY}
      s3:
        region: ${APP_AWS_S3_REGION}
management:
  endpoints:
    enabled-by-default: ${APP_ACTUATOR_ENABLE_BY_DEFAULT:false}
    web:
      exposure:
        include: ${APP_ACTUATOR_EXPOSE:*}
  prometheus:
    metrics:
      export:
        step: ${APP_ACTUATOR_PROMETHEUS_STEP:30s}
app:
  cors:
    headers: ${APP_CORS_HEADERS}
    origins: ${APP_CORS_ORIGINS}
    methods: ${APP_CORS_METHODS}
  secure:
    private-key: ${APP_PRIVATE_KEY:classpath:app.key} 
    public-key: ${APP_PUBLIC_KEY:classpath:app-pub.key}
    secure-headers: ${APP_SECURE_HEADERS:true}
  properties:
    aws-bucket: ${APP_PROPERTIES_AWS_BUCKET}
    face-similarity-threshold: ${APP_PROPERTIES_FACE_SIMILARITY_THRESHOLD:80F}
logging:
 level:
  org:
    springframework:
      web: ${APP_LOGGING_SPRING_WEB:INFO}
      security: ${APP_LOGGING_SPRING_SECURITY:INFO}